name: Test Automation Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  selenium-tests:
    name: Selenium Tests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']
        browser: ['chrome', 'firefox']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Selenium tests
      run: |
        pytest -m selenium -v -n 4 \
          --browser=${{ matrix.browser }} \
          --html=reports/selenium-${{ matrix.browser }}-report.html \
          --self-contained-html
      env:
        HEADLESS: true
        SELENIUM_BROWSER: ${{ matrix.browser }}
    
    - name: Upload Selenium test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: selenium-results-${{ matrix.python-version }}-${{ matrix.browser }}
        path: |
          reports/
          screenshots/
    
  playwright-tests:
    name: Playwright Tests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']
        browser: ['chromium', 'firefox', 'webkit']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Playwright browsers
      run: |
        playwright install chromium
        sudo apt-get update
        sudo apt-get install -y \
          libnss3 \
          libnspr4 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libcups2 \
          libdrm2 \
          libdbus-1-3 \
          libxkbcommon0 \
          libxcomposite1 \
          libxdamage1 \
          libxfixes3 \
          libxrandr2 \
          libgbm1 \
          libpango-1.0-0 \
          libcairo2 \
          libasound2t64
    
    - name: Run Playwright tests
      run: |
        pytest -m playwright -v -n 4 \
          --html=reports/playwright-${{ matrix.browser }}-report.html \
          --self-contained-html
      env:
        HEADLESS: true
        PLAYWRIGHT_BROWSER: ${{ matrix.browser }}
    
    - name: Upload Playwright test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-results-${{ matrix.python-version }}-${{ matrix.browser }}
        path: |
          reports/
          screenshots/
          videos/
    
  smoke-tests:
    name: Smoke Tests (Fast)
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Playwright browsers
      run: playwright install --with-deps chromium
    
    - name: Run smoke tests
      run: |
        pytest -m smoke -v \
          --html=reports/smoke-test-report.html \
          --self-contained-html
      env:
        HEADLESS: true
    
    - name: Upload smoke test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: smoke-test-results
        path: |
          reports/
          screenshots/

  comparison-tests:
    name: Performance Comparison
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Playwright browsers
      run: playwright install --with-deps chromium
    
    - name: Run comparison tests
      run: |
        pytest -m comparison -v -s \
          --html=reports/comparison-report.html \
          --self-contained-html
      env:
        HEADLESS: true
    
    - name: Upload comparison results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: comparison-results
        path: reports/
